### PR TITLE
Allow the package to be required directly to `template`

### LINKED ISSUE #9: Allow `template: require('html-webpack-template')`
It would be useful if you could do just `template: require('html-webpack-template')`.

I noticed your `main` is set to point at `index.ejs`. Instead you could have something like this:

**index.js**

``` javascript
var fs = require('fs');

var template = fs.readFileSync('./index.ejs', {encoding: 'utf-8'});

module.exports = template;
```

I know it's a blocking call but I don't know if it matters much.

The biggest advantage of going through a `require` like this is that it would provide a neat API. If the EJS changes for some reason, the import would still remain the same. This scheme would also work with [npm-install-webpack-plugin](https://github.com/ericclemmons/npm-install-webpack-plugin).

What do you think? I can PR this if you want.

### PR DESCRIPTION
**Pull request by bebraw**
`template: require('html-webpack-template')` should work now.

Closes #9.

### CODE REVIEW

**Comment by bebraw** [comment]
This was just a matter of resolving the path to the template. So the implementation is simpler than what I had in mind initially. The change is backwards-compatible.

**Comment by bebraw** [comment]
Any chance you could have a quick look at this over the weekend? It's a simple change, but it would help a lot with [npm-install-webpack-plugin](https://github.com/ericclemmons/npm-install-webpack-plugin) given it would allow the system to catch the `require` and get **html-webpack-plugin** installed automatically.

**Comment by bebraw** [comment]
Could you have a quick look? Seems simple enough. Sorry to pester. :smile:.

**Comment by bebraw** [comment]
Gentle poke.

**Comment by jaketrent** [comment]
Hey, cool feature.  Thanks for the add.  Nice work on the simpler implementation.  I was not seeing notifications for this, so thanks for poking me on twitter.

**Comment by jaketrent** [comment]
@bebraw Now published as v5.0.0.  Try it out, and let me know how your the new method works.

**Comment by bebraw** [comment]
@jaketrent Works great. Thanks! 👍

**Pull request merged**
