### PR TITLE
Fix comments in template file.

### PR DESCRIPTION
**Pull request by jpickwell**
The `<%# ... %>` style comments cause an error during compilation. `<% /* ... */ %>` works.

### CODE REVIEW

**Review by jaketrent — CHANGES_REQUESTED** [review]
What would you think of just removing the comments?

**Comment by jpickwell** [comment]
I tested the JS block-style comments with the `examples` directory and I'm not getting any errors. Are you still getting errors?

**Comment by jaketrent** [comment]
@jpickwell No, I wasn't getting errors.  I think it might just be nice w/o.

**Comment by jaketrent** [comment]
Great fix.  Thanks.  Published @v5.4.1

**Pull request merged**
