### PR TITLE
Fix for #26

### PR DESCRIPTION
**Pull request by BrandonBoone**
Allows you to pass a string or an object in the links array. Object
properties and values will be converted to attributes and values on the
generated `link` tags

### CODE REVIEW

**Comment by jaketrent** [comment]
@BrandonBoone I like it.  Will you make sure that the changes are documented in the examples/ and the README, and we'll get this merged.

**Comment by jaketrent** [comment]
I'm planning on versioning this as a minor change because old-style links will still work.  Let me know if you see something breaking that I don't.

**Comment by BrandonBoone** [comment]
Great, glad you like it! I updated the documentation. Let me know what you think. 

Agreed, should be a minor update as the old-style links should still work. I tested it locally and everything seems to be backwards compatible.

**Comment by jaketrent** [comment]
Looking good, @BrandonBoone .  Will you please add new usage to https://github.com/jaketrent/html-webpack-template/blob/master/examples/webpack.config.js as well?

**Comment by BrandonBoone** [comment]
I updated [webpack.config.js](https://github.com/jaketrent/html-webpack-template/pull/27/commits/9efa03bced44d3669dae7f49f1131cda4c0d325a). Let me know if you need anything else.

**Comment by jaketrent** [comment]
Published in v5.3.0

**Pull request merged**
