### PR TITLE
scripts Enhancement

### PR DESCRIPTION
**Pull request by jpickwell**
The `scripts` option is now like the `links` option, in that it allows a user to specify additional attributes for external scripts.

There are additional refactors included.

### CODE REVIEW

**Comment by jaketrent** [comment]
@jpickwell thanks for your attention here.  I'm all for making `scripts` act like `links`.  If you'd still like to do work on that, I'd appreciate a PR where that is the focus of the merge.  There is so much wrapped up in this change that I'm having a hard time grokking it and seeing all the changes.  The adjustments to the template readability could be good, but I'm seeing some changes to the functionality as well.  I would like to merge any/all of these efforts independently.  What do you think?  Still game?

**Comment by jpickwell** [comment]
I don't have a problem splitting things up. Do you want me to split these commits into separate PRs? I would do the same for #29.

I did all of this in one go, and then did selective commits through index editing. It could have been a single commit. 😆

**Comment by BrandonBoone** [comment]
While you're updating `<script >` rendering to be consistent with `<link >` rendering, you may want to contemplate updating `<meta >` rending as well. You could keep backwards compatibility by checking if `meta` is an object vs an array of objects. It would provide a certain API consistency for rendering `<script >`, `<link >`, & `<meta >` tags _(though `meta`'s existing behavior would need a breaking change if you wanted absolute consistency)_.

**Comment by jpickwell** [comment]
Yeah, I can add meta to the list of PRs I have to make. 😆

FYI: You don't need to add a space inside an element reference; e.g., `<link>` (no space).

**Comment by jaketrent** [comment]
Closing in favor of separate merges.

**Pull request closed without merging**
