### PR TITLE
Mount app in <main> instead of <div>

### PR DESCRIPTION
**Pull request by Kikobeats**
Semantically more correct 😄

### CODE REVIEW

**Comment by jaketrent** [comment]
Hey thanks for the thought around this.

Right now, I'm not seeing this as semantically more correct.  

If `main` is...

> The main content of the body of a document or application. The main content area consists of content that is directly related to or expands upon the central topic of a document or central functionality of an application.

...then I feel like it's going to be deeper in the doc, surfaced by the app, where the app can control what they point to as the "main content".

(src http://html5doctor.com/the-main-element/)

**Comment by Kikobeats** [comment]
> The HTML <main> element represents the main content of  the <body>

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

think that `<div>` was create for generic purpose

**Comment by jpickwell** [comment]
The [HTML 5.1 Specification](https://www.w3.org/TR/html/grouping-content.html#the-main-element) is quite clear about the semantic meaning of the `<main>` element:

> The main content area of a document includes content that is unique to that document and excludes content that is repeated across a set of documents such as site navigation links, copyright information, site logos and banners and search forms (unless the document or application’s main function is that of a search form).

I prefer to just use the `<body>` element with the `role` attribute set to "application".

**Comment by Kikobeats** [comment]
@jpickwell good point, close then?

**Comment by jaketrent** [comment]
Thanks for the discussion.  Closing for now.

**Pull request closed without merging**
